### ISSUE TITLE
Semantic errors tracker

### ISSUE THREAD

**Issue by lathonez** [lathonez/clicker#9]
We've got the following:

```
node_modules/ionic-framework/animations/animation.d.ts(48,51): error TS2526: A 'this' type is available only in a non-static member of a class or interface.
node_modules/ionic-framework/animations/animation.d.ts(54,51): error TS2526: A 'this' type is available only in a non-static member of a class or interface.
```

For which I've raised https://github.com/driftyco/ionic/issues/5581

and

```
node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.
```

Which looks to be solved by https://github.com/angular/angular/issues/6468, released in beta.7, though early reports suggest otherwise

**Comment by BugsBunnyBR** [comment]
I updated to beta2 and the two first errors are gone, but I am facing some problems trying to run the tests. Are you trying to update?

**Comment by lathonez** [comment]
Could you raise another issue with the description? Last night I upgraded gulp to typescript. See #19

**Comment by lathonez** [comment]
Looks like this:

`node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.`

May actually be an issue with our setup somewhere. Need to take another look.

**Comment by marcmeans** [comment]
Is this still an issue?  I upgraded my angular2 package and it went away.  When I went to do a PR it looked like it had already been done.

**Comment by lathonez** [comment]
It should go away with latest angular. I still get it https://travis-ci.org/lathonez/clicker/builds/113570052 but I don't with a new ionic app and importing all our test stuff. Need to look at it.

**Comment by lathonez** [comment]
Ah, just realised they are still on typescript 1.7.5. When I upgrade to 1.8.2 I get the error (in Ionic starter).

**Comment by lathonez** [comment]
angular .beta7 fixes.

@marcmeans not sure if this is what you were referring to but thanks for prodding me anyway.
